### ISSUE TITLE
Build failed when running flutter build apk

### ISSUE THREAD

**Issue by luis-cruzt** [sreesdas/flutter_call_number_plugin#3]
I'm getting this error when building the app to production.

> FAILURE: Build failed with an exception.                                
                                                                        

> * What went wrong:                                                      

> Execution` failed for task ':call_number:verifyReleaseResources'.        

> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed

**Comment by ghost** [comment]
> I'm getting this error when building the app to production.
> 
> > FAILURE: Build failed with an exception.
> 
> > * What went wrong:
> 
> > Execution` failed for task ':call_number:verifyReleaseResources'.
> 
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> > Android resource linking failed

This plugin is not upgraded to Androidx,
so better is fork this plugin and upgrade it 
or 
Just learn how he called the platform channel in mainactivity.java then try on your own.

**Comment by luis-cruzt** [comment]
As i can see, there was a merge previously by migrating to Android X.

**Comment by luis-cruzt** [comment]
I ended up using this package, it works very well, and no errors.
https://pub.dev/packages/intent
